{
  imports = [
    ./primary-user.nix
    ./boot.nix
    ./nix.nix
    ./sudo.nix
    ./polkit.nix
    ./sops.nix
    ./audio.nix
    ./bluetooth.nix
    ./ntp.nix
    ./console.nix
    ./env.nix
    ./fonts.nix
    ./latest-kernel.nix
    ./zram-swap.nix
    ./xkb.nix
    ./nix-ld.nix
    ./misc-tools.nix
    ./git.nix
    ./zsh.nix
    ./direnv.nix
    ./readline.nix
    ./starship.nix
    ./zoxide.nix
    ./lazygit.nix
    ./yazi.nix
    ./tmux.nix
    ./zellij.nix
    ./nvim.nix
    ./kanata.nix
    ./aerospace.nix
    ./networking.nix
    ./udev.nix
    ./libvirt.nix
    ./podman.nix
    ./docker.nix
    ./wayland.nix
    ./hyprland.nix
    ./plasma.nix
    ./sway.nix
    ./dunst.nix
    ./awww.nix
    ./swayosd.nix
    ./rofi.nix
    ./waybar.nix
    ./wlogout.nix
    ./greetd.nix
    ./avahi.nix
    ./flatpak.nix
    ./kdeconnect.nix
    ./playerctld.nix
    ./kitty.nix
    ./firefox.nix
    ./brave.nix
    ./discord.nix
    ./xdg-desktop.nix
    ./theme.nix
    ./wallust.nix
    ./desktop-tools.nix
    ./steam.nix
    ./ollama.nix
    ./sshd.nix
  ];
}
